name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'LICENSE.txt'
      - 'AUTHORS'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'LICENSE.txt'
      - 'AUTHORS'

jobs:

  linux:
    name: Linux OpenCV ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.3", "3.4", "4.0"]
    steps:
      - uses: actions/checkout@v2
      - name: run
        run: docker run -v $(pwd):/hostdir renatogarcia/opencv-swig-ci:opencv-${{ matrix.version }} /bin/bash -c "cmake /hostdir/test && cmake --build . && py.test /hostdir/test"
